/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Callback } from './callback';
import { Restriction } from './restriction';

export interface BetDeclineData extends Callback {
    /**
     * Restrictions due to which the bet was not accepted
     */
    restrictions: Array<Restriction>;
}
