/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Callback } from './callback';
import { Restriction } from './restriction';

export interface BetSettleData extends Callback {
    settleAmount: string;
    /**
     * Type of bet settlement. 1 - win, 2 - refund, 3 - lost
     */
    settleType: BetSettleBodySettleTypeEnum;
    /**
     * Restrictions due to which the bet was refunded
     */
    restrictions: Array<Restriction>;
}

export enum BetSettleBodySettleTypeEnum {
    Win = 1,
    Refund = 2,
    Lost = 3
}

