/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export enum MatchStatus {
    NotStarted = 0,
    Live = 1,
    Suspended = 2,
    Ended = 3,
    Closed = 4,
    Cancelled = 5,
    Abandoned = 6,
    Delayed = 7,
    Unknown = 8
}