/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export enum OddStatus {
    NotResulted = 0,
    Win = 1,
    Loss = 2,
    HalfWin = 3,
    HalfLoss = 4,
    Refunded = 5,
    Cancelled = 6,
    RefundedManually = 7
}

