/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OddMeta } from './odd-meta';
import { OddStatus } from './odd-status';
import { MatchStatus } from './match-status';
/**
 * 
 * @export
 * @interface Odd
 */
export interface Odd {
    oddId: string;
    oddRatio: string;
    oddStatus: OddStatus;
    matchId: string;
    matchStatus: MatchStatus;
    marketId: string;
    oddUpdatedAt: Date;
    meta: OddMeta;
}
