/* tslint:disable */
/* eslint-disable */
/**
 * Bet callback API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * System sizes selected by user while place bet. It's equal to [1] for single, [count(odds)] for express, and custom for system bet types [2, 3]
 * @export
 * @interface SystemSizes
 */
export interface SystemSizes extends Array<number> {
}
